-- 코드를 작성해주세요

SELECT EP.EMP_NO , EP.EMP_NAME , 
CASE
WHEN AVG(GR.SCORE) >= 96 THEN 'S'
WHEN AVG(GR.SCORE) >= 90 THEN 'A'
WHEN AVG(GR.SCORE) >= 80 THEN 'B'
ELSE 'C' END AS GRADE ,
CASE
WHEN AVG(GR.SCORE) >= 96  THEN EP.SAL * 0.2
WHEN AVG(GR.SCORE) >= 90 THEN EP.SAL * 0.15
WHEN AVG(GR.SCORE) >= 80  THEN EP.SAL * 0.1
ELSE 0 END AS BONUS
FROM HR_EMPLOYEES EP
JOIN HR_GRADE GR ON EP.EMP_NO = GR.EMP_NO 
GROUP BY EP.EMP_NO
ORDER BY 1;